name: Go CI
on:
  push:
    branches: [main]
    paths:
      - bench/**/*
      - webapp/go/**/*
      - development/backend-go/**/*
      - development/docker-compose-common.yml
      - development/docker-compose-go.yml
      - development/Makefile
      - .github/workflows/go.yml
  pull_request:
    paths:
      - bench/**/*
      - webapp/go/**/*
      - development/backend-go/**/*
      - development/docker-compose-common.yml
      - development/docker-compose-go.yml
      - development/Makefile
      - .github/workflows/go.yml
jobs:
  test:
    name: Build
    runs-on: [self-hosted, core2]
    steps:
      - name: cleanup
        run: |
          sudo rm -fr /home/github/work/isucon12-qualify/isucon12-qualify/go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: "setup containers"
        run: |
          make initial_data
          make up/go OPT=-d
          make install_initial_data
          make init-mysql
        working-directory: ./development
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "run bench"
        working-directory: ./development
        run: |
          make run-bench-ci
